ticket_collect/config/routes.rb
TicketCollect::Application.routes.draw do
  resources :venus

  resources :events

  root :to => 'application#landing_page'

  match 'home' => 'application#index'
end

ticket_collect/app/models/event.rb
class Event < ActiveRecord::Base
end

ticket_collect/app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
end

ticket_collect/app/models/venu.rb
class Venu < ActiveRecord::Base
end

ticket_collect/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def index
    render :layout => "home_layout"
  end
  
  def landing_page
    render :layout => false
  end
  
  def add_subscriber
    if(params[:email_or_phone])
      subscriber=Subscriber.new
      subscriber.email_or_phone=params[:email_or_phone]
      subscriber.save
    end
    flash[:notice] = "Thank you."
  end
  
end

ticket_collect/app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
end

ticket_collect/app/controllers/venus_controller.rb
class VenusController < ApplicationController
  # GET /venus
  # GET /venus.json
  def index
    @venus = Venu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @venus }
    end
  end

  # GET /venus/1
  # GET /venus/1.json
  def show
    @venu = Venu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venu }
    end
  end

  # GET /venus/new
  # GET /venus/new.json
  def new
    @venu = Venu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venu }
    end
  end

  # GET /venus/1/edit
  def edit
    @venu = Venu.find(params[:id])
  end

  # POST /venus
  # POST /venus.json
  def create
    @venu = Venu.new(params[:venu])

    respond_to do |format|
      if @venu.save
        format.html { redirect_to @venu, notice: 'Venu was successfully created.' }
        format.json { render json: @venu, status: :created, location: @venu }
      else
        format.html { render action: "new" }
        format.json { render json: @venu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /venus/1
  # PUT /venus/1.json
  def update
    @venu = Venu.find(params[:id])

    respond_to do |format|
      if @venu.update_attributes(params[:venu])
        format.html { redirect_to @venu, notice: 'Venu was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @venu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venus/1
  # DELETE /venus/1.json
  def destroy
    @venu = Venu.find(params[:id])
    @venu.destroy

    respond_to do |format|
      format.html { redirect_to venus_url }
      format.json { head :ok }
    end
  end
end

ticket_collect/app/helpers/application_helper.rb
module ApplicationHelper
end

ticket_collect/app/helpers/events_helper.rb
module EventsHelper
end

ticket_collect/app/helpers/venus_helper.rb
module VenusHelper
end

ticket_collect/app/views/application/index.html.erb
<div class="hero-unit row">
	<div class="span12 desc">
		<h1>Grab your Shows/Events.</h1>
		<p>In just one click!</p>
	</div>
</div>

<div class="row recommend">
	<div class="span6">
		<h5>Talk of the town</h5>
		<h3>Events being shared</h3>
		<div>
			<div id="fb-root"></div>
			<div id="fb-root"></div>
			<script>(function(d, s, id) {
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) return;
			  js = d.createElement(s); js.id = id;
			  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=116489561790243";
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-recommendations" data-site="eventbrite.com" data-width="300" data-height="200" data-header="false" data-border-color="whiteSmoke" data-font="arial"></div>
		</div>
	</div>
	<div class="span9">
		<h5>Popular events in</h5>
		<h3>Bangalore</h3>
		<table cellpadding="0">
		            <tbody>
		                <tr>
		                    <td class="desc_col"><a href="http://prohibition2012nye-ehometext.eventbrite.com">PROHIBITION 2012 - A NEW YEARS EVE CASINO NIGHT</a></td>
		                    <td class="date_col">Dec 31</td>
		                    <td class="attend_share_col">
								<a href="http://prohibition2012nye-ehomebtn.eventbrite.com" class="label success">picktick</a>
		                    </td>
		                </tr>
		                <tr>
		                    <td class="desc_col"><a href="http://chicagonyeballroomblitz-ehometext.eventbrite.com">Chicago New Year's Eve Party - Hyatt Regency Chicago's NYE Ballroom Blitz</a></td>
		                    <td class="date_col">Dec 31</td>
		                    <td class="attend_share_col">
		                        <a href="http://chicagonyeballroomblitz-ehomebtn.eventbrite.com" class="label success">picktick</a>
		                    </td>
		                </tr>
		                <tr>
		                    <td class="desc_col"><a href="http://nyeball2012-ehometext.eventbrite.com">San Francisco NYE Int'l Ball 2012 at PALACE HOTEL by Aykut Events</a></td>
		                    <td class="date_col">Dec 31</td>
		                    <td class="attend_share_col">
		                        <a href="http://nyeball2012-ehomebtn.eventbrite.com" class="label success">picktick</a>
		                    </td>
		                </tr>
		                <tr>
		                    <td class="desc_col"><a href="http://la-new-years-ehometext.eventbrite.com">Cleopatra's 2nd Annual 2012 New Year's Eve Ball</a></td>
		                    <td class="date_col">Dec 31</td>
		                    <td class="attend_share_col">
		                        <a href="http://la-new-years-ehomebtn.eventbrite.com" class="label success">picktick</a>
		                    </td>
		                </tr>
		                <tr>
		                    <td class="desc_col"><a href="http://restore2012-ehometext.eventbrite.com">Restore 2012 - New Year's Eve Benefit Party</a></td>
		                    <td class="date_col">Dec 31</td>
		                    <td class="attend_share_col">
		                        <a href="http://restore2012-ehomebtn.eventbrite.com" class="label success">picktick</a>
		                    </td>
		                </tr>
		                <tr>
		                    <td class="desc_col"><a href="http://2012bangaloreworkshop-ehometext.eventbrite.com">Advanced Product Management and Marketing Workshop Bangalore</a></td>
		                    <td class="date_col">Jan 12</td>
		                    <td class="attend_share_col">
		                        <a href="http://2012bangaloreworkshop-ehomebtn.eventbrite.com" class="label success">picktick</a>
		                    </td>
		                </tr>
		                <tr>
		                    <td class="desc_col"><a href="http://asad-ehometext.eventbrite.com">Hioldon</a></td>
		                    <td class="date_col">Feb 1</td>
		                    <td class="attend_share_col">
		                        <a href="http://asad-ehomebtn.eventbrite.com" class="label success">picktick</a>
		                    </td>
		                </tr>
		            </tbody>
		        </table>
	</div>
</div>

<div class="row recommend">
	<h3>The good word</h3>
	<h2>Event news & blog posts</h2>
	<div class="span5">
	    <a href="http://blog.eventbrite.com/new-years-eve-survival-guide">
            <img src="http://eventbrite-build.s3.amazonaws.com/admin/marketing/featuredblogs/nye_homepage.jpg">
            <div>Your New Year's Eve Survival Guide</div>
        </a>
	</div>
	<div class="span5">
	    <a href="http://blog.eventbrite.com/new-years-eve-survival-guide">
            <img src="http://eventbrite-build.s3.amazonaws.com/admin/marketing/featuredblogs/nye_homepage.jpg">
            <div>Your New Year's Eve Survival Guide</div>
        </a>
	</div>
	<div class="span5">
	    <a href="http://blog.eventbrite.com/new-years-eve-survival-guide">
            <img src="http://eventbrite-build.s3.amazonaws.com/admin/marketing/featuredblogs/nye_homepage.jpg">
            <div>Your New Year's Eve Survival Guide</div>
        </a>
	</div>
</div>

ticket_collect/app/views/application/landing_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketCollect</title>
	<link href='http://fonts.googleapis.com/css?family=Handlee' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="topbar">
	<div class="fill">
		<div class="container">
			<a class="brand fonter" href="#">PickTicks</a>
		</div>
	</div>
</div>

<div class="container">
	<div class="hero-unit row">
		<div class="span4 desc">
			<h1>Grab your Shows/Events.</h1>
			<p>In just one click!</p>
		</div>
		<div class="span9">
		<p>Sign up for exclusive access to our beta release in the coming weeks!</p>
		<form>
			<fieldset>
				<div class="clearfix">
					<div class="input">
						<div class="input-prepend">
							<span class="add-on">email/phone</span>
							<input class="medium" id="prependedInput" name="prependedInput" size="16" type="text" />
							<a class="btn info">Subscribe »</a>
						</div>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
	</div>
	<div class="social row">
		<div class="span12">
			<h2><%= COMPANY_NAME %></h2>
			<p><%= PRODUCT_INFO%></p>
		</div>
		<div class="span3">
			<h5>Share</h5>
			<div style="float:right">
				<span style="display:block;padding:5px">
					<div id="fb-root"></div>
					<script>(function(d, s, id) {
					  var js, fjs = d.getElementsByTagName(s)[0];
					  if (d.getElementById(id)) return;
					  js = d.createElement(s); js.id = id;
					  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=116489561790243";
					  fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));</script>
					<div class="fb-like" data-href="http://www.facebook.com/arvind.thatikonda" data-send="true" data-layout="button_count" data-width="100" data-show-faces="false" data-font="trebuchet ms"></div>
				</span>
				<span style="display:block;padding:5px">
					<a href="https://twitter.com/share" class="twitter-share-button" data-via="karthik001" data-hashtags="picktick">Tweet</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>			</span>
				<span style="display:block;padding:5px">
					<script src="http://platform.linkedin.com/in.js" type="text/javascript"></script>
					<script type="IN/Share" data-counter="right"></script>
				</span>
				<span style="display:block; padding:5px">
					<!-- Place this tag where you want the +1 button to render -->
					<g:plusone annotation="inline" width="120"></g:plusone>

					<!-- Place this render call where appropriate -->
					<script type="text/javascript">
					  (function() {
					    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
					    po.src = 'https://apis.google.com/js/plusone.js';
					    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
					  })();
					</script>
				</span>
			</div>
		</div>
	</div>
	
<!--footer>
        <p>© Company 2011</p>
</footer-->
</body>
</html>

ticket_collect/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<fieldset>
	<legend>Create Event</legend>
	<div class="clearfix">
      <label for="xlInput">Name</label>
      <div class="input">
		<%= f.text_field :name, :class=>'xlarge' %>
      </div>
    </div>
	<div class="clearfix">
      <label for="xlInput">Description</label>
      <div class="input">
		<%= f.text_field :description, :class=>'xlarge' %>
      </div>
    </div>
	<div class="clearfix">
      <label for="xlInput">Start Date</label>
      <div class="input">
		<%= f.date_select :start_date, :class=>'xlarge' %>
      </div>
    </div>
	<div class="clearfix">
      <label for="xlInput">End Date</label>
      <div class="input">
		<%= f.date_select :end_date, :class=>'xlarge' %>
      </div>
    </div>
</fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ticket_collect/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

ticket_collect/app/views/events/index.html.erb
<div class="row">
<div class="span12">Category 1</div>
<% @events.each do |event| %>
  <div class="event span4">
    <h2><%= event.name %></h2>
    <p><%= event.description %></p>
    <p>
		<%= link_to 'View details »', event, :class=>'btn' %>
		<!--
		<td><%= link_to 'Edit', edit_event_path(event) %></td>
	    <td><%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %></td>-->
	</p>
  </div>
<% end %>
</div>
<%= link_to 'New Event', new_event_path %>

ticket_collect/app/views/events/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', events_path %>

ticket_collect/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Start date:</b>
  <%= @event.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @event.end_date %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

ticket_collect/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketCollect</title>
	<link href='http://fonts.googleapis.com/css?family=Handlee' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="topbar">
	      <div class="topbar-inner">
	        <div class="container-fluid">
	          <a class="brand" href="#">Project name</a>
	          <ul class="nav">
	            <li class="active"><a href="#">Home</a></li>
	            <li><a href="#about">About</a></li>
	            <li><a href="#contact">Contact</a></li>
	          </ul>
	          <p class="pull-right">Logged in as <a href="#">username</a></p>
	        </div>
	      </div>
	    </div>
		<div class="container-fluid">

		      <div class="sidebar">
		        <div class="well">
		          <h5>Sidebar</h5>
		          <ul>
		            <li><a href="#">Link</a></li>
		            <li><a href="#">Link</a></li>
		            <li><a href="#">Link</a></li>
		            <li><a href="#">Link</a></li>
		          </ul>
		          <h5>Sidebar</h5>
		          <ul>
		            <li><a href="#">Link</a></li>
		            <li><a href="#">Link</a></li>
		            <li><a href="#">Link</a></li>
		            <li><a href="#">Link</a></li>
		            <li><a href="#">Link</a></li>
		            <li><a href="#">Link</a></li>
		          </ul>
		          <h5>Sidebar</h5>
		          <ul>
		            <li><a href="#">Link</a></li>
		            <li><a href="#">Link</a></li>
		          </ul>
		        </div>
		      </div>
		      <div class="content">
				<%= yield %>
		        <!-- Main hero unit for a primary marketing message or call to action
		        <div class="hero-unit">
		          <h1>Event Name</h1>
		          <p>Vestibulum id ligula porta felis euismod semper. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
		          <p><a class="btn primary large">Learn more »</a></p>
		        </div>
 -->
		        <!-- Example row of columns 
		        <div class="row">
				<div class="span12">Category 1</div>
		          <div class="event span6">
		            <h2>Event 1</h2>
		            <p>Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
		            <p><a class="btn" href="#">View details »</a></p>
		          </div>
		        </div>

		        <hr>
		        <div class="row">
				<div class="span12">Category 2</div>
		          <div class="span6">
		            <h2>Heading</h2>
		            <p>Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
		            <p><a class="btn" href="#">View details »</a></p>
		          </div>
		        </div>
			-->
		        <footer>
		          <p>© Company 2011</p>
		        </footer>
		      </div>
		    </div>
</body>
</html>

ticket_collect/app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketCollect</title>
	<link href='http://fonts.googleapis.com/css?family=Handlee' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="topbar">
	      <div class="topbar-inner">
	        <div class="container-fluid">
	          <a class="brand" href="#">Project name</a>
	          <ul class="nav secondary-nav">
	            <li><a href="#about">Find Events</a></li>
	            <li><a href="#contact">Learn more</a></li>
				<li><a href="#contact">Help</a></li>
				<li><a href="#contact">Signup</a></li>
				<li><a href="#contact">Login</a></li>
	          </ul>
	        </div>
	      </div>
	    </div>
		<div class="container">
			<div class="content">
				<%= yield %>
		        <!-- Main hero unit for a primary marketing message or call to action
		        <div class="hero-unit">
		          <h1>Event Name</h1>
		          <p>Vestibulum id ligula porta felis euismod semper. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
		          <p><a class="btn primary large">Learn more »</a></p>
		        </div>
 -->
		        <!-- Example row of columns 
		        <div class="row">
				<div class="span12">Category 1</div>
		          <div class="event span6">
		            <h2>Event 1</h2>
		            <p>Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
		            <p><a class="btn" href="#">View details »</a></p>
		          </div>
		        </div>

		        <hr>
		        <div class="row">
				<div class="span12">Category 2</div>
		          <div class="span6">
		            <h2>Heading</h2>
		            <p>Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
		            <p><a class="btn" href="#">View details »</a></p>
		          </div>
		        </div>
			-->
		        <footer>
		          <div class="row">
		          	<div class="span3">
						<h6>About us</h6>
						<ul>
							<li><a>About us</a></li>
							<li><a>Contact us</a></li>
							<li><a>Pricing</a></li>
							<li><a>Referal program</a></li>
							<li><a>Press</a></li>
						</ul>
					</div>
					<div class="span4">
						<h6>How To</h6>
						<ul>
							<li><a>Sell tickets online</a></li>
							<li><a>Free online event registration</a></li>
							<li><a>Promote Events Online</a></li>
							<li><a>Collect Donations online</a></li>
							<li><a>Send email invitations</a></li>
							<li><a>Publish Event to Facebook</a></li>
						</ul>
					</div>
					<div class="span4">
						<h6>Resources</h6>
						<ul>
							<li><a>Help Center</a></li>
							<li><a>Eventbrite Blog</a></li>
							<li><a>Partnerships and Resources</a></li>
							<li><a>Eventbrite on Twitter</a></li>
							<li><a>Developer API</a></li>
							<li><a>Site Map</a></li>
						</ul>
					</div>					
		          </div>
		        </footer>
		      </div>
		    </div>
</body>
</html>

ticket_collect/app/views/venus/_form.html.erb
<%= form_for(@venu) do |f| %>
  <% if @venu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venu.errors.count, "error") %> prohibited this venu from being saved:</h2>

      <ul>
      <% @venu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :addresss %><br />
    <%= f.text_field :addresss %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ticket_collect/app/views/venus/edit.html.erb
<h1>Editing venu</h1>

<%= render 'form' %>

<%= link_to 'Show', @venu %> |
<%= link_to 'Back', venus_path %>

ticket_collect/app/views/venus/index.html.erb
<h1>Listing venus</h1>

<table>
  <tr>
    <th>Address1</th>
    <th>Addresss</th>
    <th>City</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @venus.each do |venu| %>
  <tr>
    <td><%= venu.address1 %></td>
    <td><%= venu.addresss %></td>
    <td><%= venu.city %></td>
    <td><%= venu.state %></td>
    <td><%= link_to 'Show', venu %></td>
    <td><%= link_to 'Edit', edit_venu_path(venu) %></td>
    <td><%= link_to 'Destroy', venu, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Venu', new_venu_path %>

ticket_collect/app/views/venus/new.html.erb
<h1>New venu</h1>

<%= render 'form' %>

<%= link_to 'Back', venus_path %>

ticket_collect/app/views/venus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address1:</b>
  <%= @venu.address1 %>
</p>

<p>
  <b>Addresss:</b>
  <%= @venu.addresss %>
</p>

<p>
  <b>City:</b>
  <%= @venu.city %>
</p>

<p>
  <b>State:</b>
  <%= @venu.state %>
</p>


<%= link_to 'Edit', edit_venu_path(@venu) %> |
<%= link_to 'Back', venus_path %>